// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCaPr0Nf4omSHLl2-cSIzJpiSLkPhdBAaQ',
    appId: '1:1023115742314:web:b11935f11dfed68ebd8e13',
    messagingSenderId: '1023115742314',
    projectId: 'sds-sdsd-sdsds',
    authDomain: 'sds-sdsd-sdsds.firebaseapp.com',
    storageBucket: 'sds-sdsd-sdsds.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCp1inukypzwOMRHN8-XC2AntvSkuoV98c',
    appId: '1:1023115742314:android:f7a5c3e0864c4b92bd8e13',
    messagingSenderId: '1023115742314',
    projectId: 'sds-sdsd-sdsds',
    storageBucket: 'sds-sdsd-sdsds.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyD00IzfhoD1wrhN1Jrn4b57l0VOn6o9L6k',
    appId: '1:1023115742314:ios:222a71fb62df809bbd8e13',
    messagingSenderId: '1023115742314',
    projectId: 'sds-sdsd-sdsds',
    storageBucket: 'sds-sdsd-sdsds.appspot.com',
    iosClientId: '1023115742314-tn7aeklfuf8mekg3s2pvv7bnchen75f8.apps.googleusercontent.com',
    iosBundleId: 'com.example.messageWithFirebase',
  );
}
